name: Build Binaries

on:
  workflow_call:
    inputs:
      release_name:
        description: "allow setting the release name"
        default: "latest"
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@v4
        with:
          name: Firmware

      - name: Checkout Userspace
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Get next version
        uses: reecetech/version-increment@2024.9.2
        id: version
        with:
          scheme: calver

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: Latest QMK Firmware
          tag_name: ${{ steps.version.outputs.version }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          make_latest: ${{ github.ref_name == github.event.repository.default_branch }}
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
